version: '3.8'

services:
  alpha:
    build: .
    image: conti-test
    container_name: alpha
    hostname: alpha
    networks:
      conti-test:
        ipv4_address: 172.16.100.140
    volumes:
      - charlie_data:/opt/data
    restart: always
    deploy:
      resources:
        reservations:
          memory: 256M
        limits:
          memory: 512M
          
  bravo:
    build: .
    image: conti-test
    container_name: bravo
    hostname: bravo
    networks:
      conti-test:
        ipv4_address: 172.16.100.141
    restart: always
    deploy:
      resources:
        limits:
          cpus: '0.1'
          memory: 4G
    depends_on:
      alpha:
        condition: service_healthy

  charlie:
    build: .
    image: conti-test
    container_name: charlie
    hostname: charlie
    networks:
      conti-test:
        ipv4_address: 172.16.100.142
    volumes:
      - charlie_data:/opt/data
    environment:
      CONTI_ENV: ${CONTI_ENV:-prod}
      CONTI_DB_NAME: ${CONTI_DB_NAME}
    restart: always
    deploy:
      resources:
        reservations:
          memory: 512M
        limits:
          memory: 1G
    depends_on:
      bravo:
        condition: service_healthy

networks:
  conti-test:
    ipam:
      config:
        - subnet: 172.16.100.128/26

volumes:
  charlie_data:
    driver: local