---
- hosts: east
  tasks:
    - name: Set Eastern message
      copy:
        content: "Eastern promises.\n"
        dest: /etc/motd

- hosts: west
  tasks:
    - name: Set Western message
      copy:
        content: "Once upon a time in the west.\n"
        dest: /etc/motd
